spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.24.29.109:17963/clean_read?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: cleaner
    password: QAZ!@#wsx