/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 02-十一月-2015 21:44:48 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `User` CASCADE
;

/* Create Tables */

CREATE TABLE `User`
(
	`email` VARCHAR(100) NOT NULL COMMENT '电子邮箱，主键',
	`username` VARCHAR(100) NOT NULL COMMENT '用户名，可重复',
	`password` VARCHAR(50) NOT NULL COMMENT '密码',
	CONSTRAINT `PK_User` PRIMARY KEY (`email`)
)
COMMENT='用户表；clean-read系统中注册的用户'

;

SET FOREIGN_KEY_CHECKS=1 ;
